[theme]
base="light"
font="monospace"
primaryColor="#7BA46C"#7BA46C #74512D
backgroundColor="#FBF5DD"#FFFFFF #FEFAF6
secondaryBackgroundColor="#A6CDC6"#ABD1C6 #AF8F6F
textColor="#16404D"#004643 #543310